/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'ExpenseCreateApi': ApiRouteHandler<{ description: string; amount: number; userId: string }, ApiResponse<201, { data?: { id: string; description: string; amount: number; userId: string }; message: string; success: boolean }> | ApiResponse<500, { data?: unknown; message: string; success: boolean }>, never>
  }
}